# Generated by Django 2.1.6 on 2019-05-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
