# Generated by Django 2.1.6 on 2019-05-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
