# Generated by Django 2.1.6 on 2019-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0004_auto_20190530_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='old_user', max_length=200),
        ),
    ]
